version: "3"
services:
  redis:
    image: redis:alpine
    container_name: autolitigator-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: autolitigator-db
    environment:
      POSTGRES_DB: autolitigator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
